### ISSUE TITLE
FAQ page fails to load on Waterfox

### ISSUE THREAD

**Issue by badolsmito** [sevora/deebait#7]
![deebait2](https://user-images.githubusercontent.com/99145855/202546620-317ab700-91d0-4549-a2a1-93d46c0606fc.png)

**Comment by sevora** [comment]
I'll need a few more details to figure that out as it seems to always work in Chrome.

**Comment by badolsmito** [comment]
I don't know how to provide you with the details because I don't do web dev.

**Comment by sevora** [comment]
Alright. That's fine. I'll figure it out later.
